Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,11 +4,16 @@ on:
   push:
     branches: ["main"]
 
+permissions:
+  contents: write
+
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0  # necessário para deploy
 
       - name: Setup Node
         uses: actions/setup-node@v3
@@ -19,10 +24,9 @@ jobs:
       - run: npm run build
 
       - name: Copy 404.html
-        run: cp 404.html dist/
+        run: cp 404.html dist/ || echo "404.html not found, skipping"
 
       - name: Deploy
         uses: peaceiris/actions-gh-pages@v3
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./dist
+          githu
